version: 0.2  # BuildSpec 파일 버전 (현재 최신 버전)

phases:
  install:
    commands:
      - echo Setting timezone to Asia/Seoul...
      - export TZ=Asia/Seoul  # 시간대를 한국 표준시로 설정

      - echo Current time is $(date)

      - echo Getting commit hash and timestamp...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TIMESTAMP=$(date +%y%m%d_%H%M%S)
      - export IMAGE_TAG="${COMMIT_HASH}_${TIMESTAMP}"
      - echo "IMAGE_TAG=$IMAGE_TAG (KST)"  # 생성된 태그 출력

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."

      - aws --version

      - echo "AWS Account ID=$AWS_ACCOUNT_ID"          # AWS 계정 ID
      - echo "AWS Region=$AWS_DEFAULT_REGION"          # AWS 리전
      - echo "Image Repository=$IMAGE_REPO_NAME"       # ECR 리포지토리명
      - echo "Container Name=$CONTAINER_NAME"          # ECS 컨테이너명

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

      - echo "Repository URI=$REPOSITORY_URI"
      - echo "Image tag=$IMAGE_TAG"

  build:
    commands:
      - echo "Build started on $(date)"

      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Build completed on $(date)"

      - echo "Pushing the Docker images..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo "Writing image definitions file..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

      - echo "Image definitions file created:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
