import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ko: {
    // Navbar
    'nav.universities': '학교 모아보기',
    'nav.universities.all': '전체 학교 보기',
    'nav.universities.compare': '학교 비교하기',
    'nav.universities.map': '지도에서 보기',
    
    // University Map Page
    'map.title': '대학 지도',
    'map.subtitle': '미국 전역의 주요 대학 위치와 학비 정보를 한눈에 확인하세요',
    'map.universities.count': '개 대학 표시',
    'map.reset.view': '위치 초기화',
    'nav.profile': '프로필 분석',
    'nav.consulting': '컨설팅 추천',
    'nav.housing': '주거 지원',
    'nav.dashboard': '대시보드',
    'nav.login': '로그인',
    'nav.logout': '로그아웃',
    'nav.language': 'English',
    
    // HomePage - Hero
    'home.hero.subtitle': 'AI가 분석하는 나만의 유학 로드맵',
    'home.hero.title': '꿈의 대학, 현실이 됩니다',
    'home.hero.description': '복잡한 입시 정보를 한눈에, 개인 맞춤 유학 플랜까지\n프렙라운지와 함께 성공적인 미국 유학을 시작하세요.',
    'home.hero.cta.predict': '합격 예측 해보기',
    'home.hero.cta.input': '입시 정보 둘러보기',
    
    // HomePage - Calculator
    'home.calculator.title': '합격 가능성 미리보기',
    'home.calculator.subtitle': '성적 정보를 입력하고 프로필 점수를 확인해 보세요.',
    'home.calculator.gpa': 'GPA (4.0점 만점)',
    'home.calculator.sat.ebrw': 'SAT EBRW (800점 만점)',
    'home.calculator.sat.math': 'SAT Math (800점 만점)',
    'home.calculator.score': '프로필 점수',
    'home.calculator.score.total': '/ 100점',
    'home.calculator.description': 'GPA와 SAT 점수를 기반으로 한 간단한 계산입니다.\n과외활동, 에세이, 개인화된 대학 추천을 포함한 종합적인\n분석을 위해서는 전체 프로필을 완성해주세요.',
    'home.calculator.button': '합격 가능성 상세 분석하기',
    
    // HomePage - Features
    'home.features.title': '핵심 서비스',
    'home.features.subtitle': '프렙라운지는 국제학교 학생들의 성공적인 대입을 위한 다양한 서비스를 제공합니다.',
    'home.features.schools.title': '학교 정보\n모아보기',
    'home.features.schools.description': '입학에 필요한 서류와 지원 일정 등, 미국 1,200여 개 대학의 입학 정보를 한눈에 확인하세요.',
    'home.features.profile.title': '개인 맞춤\n프로필 분석',
    'home.features.profile.description': '학생의 성적과 대외활동 경력을 토대로 AI가 입학 가능성을 분석해줘요.',
    'home.features.consulting.title': '컨설팅 프로그램\n비교/추천',
    'home.features.consulting.description': '국내 컨설팅 학원을 비교하고 프로필 강화를 위한 최적의 프로그램을 만나보세요.',
    'home.features.link': '바로가기 →',
    
    // HomePage - Majors
    'home.majors.title': '전공 선택, 아직도 고민되시나요?',
    'home.majors.subtitle': '간단한 테스트로 나에게 맞는 전공을 찾아보세요.\n* 평균 연봉과 취업률은 추정치입니다.',
    'home.majors.engineering': '공학 (Engineering)',
    'home.majors.engineering.specializations': '컴퓨터 과학, 전기공학, 기계공학',
    'home.majors.engineering.salary': '평균 연봉 $85,000',
    'home.majors.engineering.employment': '취업률 94%',
    'home.majors.engineering.opt': 'STEM OPT 3년 가능',
    'home.majors.business': '경영 (Business)',
    'home.majors.business.specializations': '경영학, 경제학, 금융학, 마케팅',
    'home.majors.business.salary': '평균 연봉 $78,000',
    'home.majors.business.employment': '취업률 88%',
    'home.majors.business.networking': '네트워킹 기회 풍부',
    'home.majors.liberal': '인문학 (Liberal Arts)',
    'home.majors.liberal.specializations': '문학, 철학, 역사, 언어학, 문화연구',
    'home.majors.liberal.salary': '평균 연봉 $65,000',
    'home.majors.liberal.employment': '취업률 82%',
    'home.majors.liberal.thinking': '비판적 사고력 개발',
    'home.majors.natural': '자연과학 (Natural Sciences)',
    'home.majors.natural.specializations': '생물학, 화학, 물리학, 수학, 환경과학',
    'home.majors.natural.salary': '평균 연봉 $72,000',
    'home.majors.natural.employment': '취업률 85%',
    'home.majors.natural.graduate': '대학원 진학률 높음',
    'home.majors.social': '사회과학 (Social Sciences)',
    'home.majors.social.specializations': '심리학, 정치학, 사회학, 국제관계학',
    'home.majors.social.salary': '평균 연봉 $68,000',
    'home.majors.social.employment': '취업률 83%',
    'home.majors.social.problem': '사회 문제 해결',
    
    // Student Profile Page
    'profile.hero.title': '프로필 분석',
    'profile.hero.description': '교과 및 비교과 프로필을 완성하여 종합적인 프로필 점수와 개인 맞춤 대학 추천을 받아보세요.',
    'profile.score.label': '프로필 점수',
    'profile.score.excellent': '우수함',
    'profile.score.very-good': '매우 좋음',
    'profile.score.good': '좋음',
    'profile.score.fair': '보통',
    'profile.score.needs-improvement': '개선 필요',
    'profile.checklist.title': '지원서 구성 요소 체크리스트',
    'profile.checklist.description': '완료했거나 가지고 있는 항목을 체크하세요. 지원 준비 상태를 확인하는 데 도움이 됩니다.\n모든 항목이 필수는 아니며 학교마다 요구 사항이 다를 수 있습니다.',
    'profile.checklist.gpa': '고등학교 GPA',
    'profile.checklist.gpa.desc': 'Secondary school GPA',
    'profile.checklist.rank': '고등학교 석차',
    'profile.checklist.rank.desc': 'Secondary school rank',
    'profile.checklist.transcript': '고등학교 성적표',
    'profile.checklist.transcript.desc': 'Secondary school transcript',
    'profile.checklist.college-prep': '대학 준비 프로그램',
    'profile.checklist.college-prep.desc': 'College-preparatory program',
    'profile.checklist.recommendations': '추천서',
    'profile.checklist.recommendations.desc': 'Recommendations',
    'profile.checklist.extracurriculars': '대외활동',
    'profile.checklist.extracurriculars.desc': 'Extracurricular activities',
    'profile.checklist.essay': '자기소개서/에세이',
    'profile.checklist.essay.desc': 'Personal statement or essay',
    'profile.checklist.test-scores': '시험 점수',
    'profile.checklist.test-scores.desc': 'Test scores',
    'profile.tabs.academic': '교과',
    'profile.tabs.non-academic': '비교과',
    'profile.academic.title': '교과 정보',
    'profile.academic.gpa': 'GPA (4.0 만점) *',
    'profile.academic.major': '희망 전공',
    'profile.academic.major.placeholder': '전공을 선택하세요',
    'profile.academic.major.cs': '컴퓨터과학',
    'profile.academic.major.engineering': '공학',
    'profile.academic.major.business': '경영학',
    'profile.academic.major.medicine': '의학',
    'profile.academic.major.liberal-arts': '인문학',
    'profile.academic.major.sciences': '자연과학',
    'profile.academic.major.math': '수학',
    'profile.academic.major.other': '기타',
    'profile.academic.test': '입학 시험',
    'profile.academic.test.placeholder': '시험을 선택하세요 (선택사항)',
    'profile.academic.sat.ebrw': 'SAT EBRW (800점 만점)',
    'profile.academic.sat.math': 'SAT Math (800점 만점)',
    'profile.academic.act': 'ACT 점수 (36점 만점)',
    'profile.academic.english': '영어 능력 시험 (국제학생용)',
    'profile.academic.english.placeholder': '시험을 선택하세요 (선택사항)',
    'profile.academic.english.score': '점수',
    'profile.non-academic.title': '비교과 정보',
    'profile.non-academic.essay': '자기소개서 (Common App 에세이)',
    'profile.non-academic.essay.placeholder': '자기소개서를 작성하세요...',
    'profile.non-academic.essay.count': '글자',
    'profile.extracurriculars.title': '대외활동',
    'profile.extracurriculars.add': '활동 추가',
    'profile.extracurriculars.activity': '활동',
    'profile.extracurriculars.type': '활동 유형',
    'profile.extracurriculars.type.sports': '스포츠',
    'profile.extracurriculars.type.arts': '예술',
    'profile.extracurriculars.type.community': '봉사활동',
    'profile.extracurriculars.type.research': '연구',
    'profile.extracurriculars.type.academic': '학술 동아리',
    'profile.extracurriculars.type.leadership': '리더십',
    'profile.extracurriculars.type.work': '근무 경험',
    'profile.extracurriculars.type.other': '기타',
    'profile.extracurriculars.name': '활동명',
    'profile.extracurriculars.name.placeholder': '예: 축구부',
    'profile.extracurriculars.grades': '참여 학년 (해당하는 모든 학년 선택)',
    'profile.extracurriculars.grade': '학년',
    'profile.extracurriculars.recognition': '인정 수준',
    'profile.extracurriculars.recognition.local': '지역',
    'profile.extracurriculars.recognition.regional': '광역',
    'profile.extracurriculars.recognition.national': '전국',
    'profile.extracurriculars.recognition.international': '국제',
    'profile.extracurriculars.hours': '주당 시간',
    'profile.extracurriculars.description': '설명',
    'profile.extracurriculars.description.placeholder': '역할과 성과를 설명하세요...',
    'profile.extracurriculars.empty': '아직 추가된 대외활동이 없습니다.',
    'profile.extracurriculars.empty.action': '"활동 추가"를 클릭하여 시작하세요.',
    'profile.recommendations.title': '추천서',
    'profile.recommendations.add': '추천서 추가',
    'profile.recommendations.letter': '추천서',
    'profile.recommendations.source': '추천인',
    'profile.recommendations.source.teacher': '교사',
    'profile.recommendations.source.counselor': '상담교사',
    'profile.recommendations.source.principal': '교장',
    'profile.recommendations.source.coach': '코치',
    'profile.recommendations.source.employer': '고용주',
    'profile.recommendations.source.other': '기타',
    'profile.recommendations.depth': '관계의 깊이',
    'profile.recommendations.depth.deep': '깊이 알고 있음',
    'profile.recommendations.depth.somewhat': '어느 정도 알고 있음',
    'profile.recommendations.depth.barely': '거의 모름',
    'profile.recommendations.relevance': '과목/분야 관련성',
    'profile.recommendations.relevance.highly': '희망 전공과 매우 관련 있음',
    'profile.recommendations.relevance.somewhat': '희망 전공과 어느 정도 관련 있음',
    'profile.recommendations.relevance.not': '관련 없음 또는 해당 없음',
    'profile.recommendations.empty': '아직 추가된 추천서가 없습니다.',
    'profile.recommendations.empty.action': '"추천서 추가"를 클릭하여 시작하세요.',
    'profile.legacy.title': '가족 내 동문 여부',
    'profile.legacy.yes': '예',
    'profile.legacy.no': '아니오',
    'profile.citizenship.title': '시민권',
    'profile.citizenship.domestic': '국내',
    'profile.citizenship.international': '국제',
    'profile.save': '프로필 점수 계산하기',
    'profile.comparison.title': '학교 비교',
    'profile.comparison.search.placeholder': '학교명으로 검색...',
    'profile.comparison.search.button': '검색',
    'profile.comparison.results': '검색 결과',
    'profile.comparison.ranking': '합격률',
    'profile.comparison.category.safety': '안전권',
    'profile.comparison.category.target': '적정권',
    'profile.comparison.category.reach': '도전권',
    'profile.comparison.required-score': '필요 점수:',
    'profile.comparison.my-score': '내 점수:',
    'profile.comparison.ratio': '비율:',
    'profile.comparison.no-results': '와 일치하는 학교를 찾을 수 없습니다',
    'profile.comparison.no-results.action': '다른 이름으로 검색해보세요.',
    'profile.comparison.empty': '프로필을 완성하고 비교 결과를 확인하세요.',
    
    // Housing Page
    'housing.hero.subtitle': 'Searching for your Dream Home',
    'housing.hero.title': '캠퍼스 근처, 완벽한 집을 찾아보세요.',
    'housing.hero.description': '대학 주변의 모든 매물을 한눈에!\n온라인으로 쉽고 간편하게 원하는 조건에 맞는 집을 구경하세요.',
    'housing.hero.button': '지금 바로 매물 찾기',
    'housing.availability.notice': '현재 캘리포니아와 조지아주의 매물만 제공됩니다',
    'housing.search.title': '원하는 조건으로 간편하게 검색',
    'housing.search.description': '캘리포니아 또는 조지아 지역의 도시를 검색하세요',
    'housing.search.placeholder': '예: Los Angeles, Atlanta, Fresno, Savannah',
    'housing.search.error.invalid-state': '죄송합니다. 현재 캘리포니아(CA)와 조지아(GA)주의 매물만 이용 가능합니다.',
    'housing.search.error.examples': '예시: Fresno, Los Angeles, San Francisco (CA) • Atlanta, Savannah, Athens (GA)',
    'housing.listings.title': '하버드 근처 새로 나온 집',
    'housing.badge.available': '입주가능',
    'housing.price.period': '/월',
    'housing.button.details': '자세히 보기',
    'housing.empty.title': '에서 매물을 찾을 수 없습니다',
    'housing.empty.description': '현재 캘리포니아와 조지아주의 매물만 제공됩니다.',
    'housing.empty.examples': '캘리포니아: Fresno, Los Angeles, San Francisco, San Diego, Sacramento',
    'housing.empty.examples.ga': '조지아: Atlanta, Savannah, Athens, Augusta, Columbus',
    'housing.features.title': '더 쉽고 빠르게 집을 찾는 방법',
    'housing.features.location.title': '대학교 주변 매물만 모아서',
    'housing.features.location.description': '대학교 지역을 검색하면 캠퍼스 주변 매물만 자동으로 필터링됩니다.\n수천 개의 불필요한 매물 대신 정말 필요한 집만 찾아보세요.',
    'housing.features.search.title': '원하는 조건으로 검색',
    'housing.features.search.description': '예산, 방 개수, 거리, 집 타입 등 원하는 조건을 선택하면 딱 맞는 매물만 보여드립니다.\n복잡한 검색 없이 클릭 몇 번으로 완벽한 집을 찾으세요.',
    'housing.features.expert.title': '처음이라면 전문가와 상담',
    'housing.features.expert.description': '미국 집 구하기가 처음이라 막막하신가요? 현지 부동산 전문가와 카카오톡으로 편하게 상담할 수 있습니다.',
    
    // Universities Page
    'universities.title': '대학 찾기',
    'universities.description': '미국 대학을 둘러보고 나에게 맞는 학교를 찾아보세요.',
    'universities.search.placeholder': '이름 또는 지역으로 검색',
    'universities.filter.title': '필터',
    'universities.filter.type': '소유 형태',
    'universities.filter.type.private': '사립',
    'universities.filter.type.public': '공립',
    'universities.filter.sort': '정렬',
    'universities.filter.sort.default': '추천순',
    'universities.filter.sort.name-asc': '가나다순 (ㄱ-ㅎ)',
    'universities.filter.sort.name-desc': '가나다순 (ㅎ-ㄱ)',
    'universities.filter.sort.sat-asc': 'SAT 범위순 (오름차순)',
    'universities.filter.sort.sat-desc': 'SAT 범위순 (내림차순)',
    'universities.filter.tuition': '학비',
    'universities.filter.sat': 'SAT 범위',
    'universities.results': '전체 {total}개 학교 중 {filtered}개 학교',
    'universities.acceptance': '합격률:',
    'universities.tuition': '학비:',
    'universities.sat': 'SAT 범위:',
    'universities.act': 'ACT 범위:',
    'universities.empty.title': '해당되는 학교가 없습니다',
    'universities.empty.description': '필터를 해제하고 다시 시도해보세요.',
    'universities.empty.reset': '필터 해제',
    
    // University Profile Page
    'university.back': '학교 목록으로 돌아가기',
    'university.commonapp.yes': 'Common App 지원 가능',
    'university.commonapp.no': '학교별 지원서 필요',
    'university.compare': '비교하기',
    'university.addToFavorites': '즐겨찾기 추가',
    'university.removeFromFavorites': '즐겨찾기 제거',
    'university.location': '위치',
    'university.type': '유형',
    'university.size': '규모',
    'university.stat.acceptance': '합격률',
    'university.stat.tuition': '등록금',
    'university.stat.sat': 'SAT 범위',
    'university.stat.act': 'ACT 범위',
    'university.stat.gpa': '평균 GPA',
    'university.requirements.title': '지원 요건',
    'university.requirements.gpa': '고등학교 GPA',
    'university.requirements.required': '필수',
    'university.info.title': '학업 정보',
    'university.info.graduation': '졸업률',
    'university.notfound.title': '학교를 찾을 수 없습니다',
    'university.notfound.back': '학교 목록으로 돌아가기',
    
    // Login Page
    'login.title': '로그인',
    'login.subtitle': '프렙라운지에 다시 오신 것을 환영합니다',
    'login.email': '이메일',
    'login.email.placeholder': '이메일 주소를 입력하세요',
    'login.password': '비밀번호',
    'login.password.placeholder': '비밀번호를 입력하세요',
    'login.remember': '로그인 상태 유지',
    'login.forgot': '비밀번호를 잊으셨나요?',
    'login.button': '로그인',
    'login.loading': '로그인 중...',
    'login.signup.prompt': '아직 계정이 없으신가요?',
    'login.signup.link': '회원가입',
    'login.error.invalid': '이메일 또는 비밀번호가 올바르지 않습니다.',
    'login.error.general': '오류가 발생했습니다. 다시 시도해 주세요.',
    
    // Signup Page
    'signup.title': '회원가입',
    'signup.subtitle': '꿈의 대학으로 가는 여정을 시작하세요',
    'signup.name': '이름',
    'signup.name.placeholder': '이름을 입력하세요',
    'signup.email': '이메일',
    'signup.email.placeholder': '이메일 주소를 입력하세요',
    'signup.password': '비밀번호',
    'signup.password.placeholder': '비밀번호를 입력하세요',
    'signup.confirm': '비밀번호 확인',
    'signup.confirm.placeholder': '비밀번호를 다시 입력하세요',
    'signup.terms.agree': '동의합니다',
    'signup.terms.service': '서비스 이용약관',
    'signup.terms.and': '및',
    'signup.terms.privacy': '개인정보 처리방침',
    'signup.button': '계정 만들기',
    'signup.loading': '계정 생성 중...',
    'signup.login.prompt': '이미 계정이 있으신가요?',
    'signup.login.link': '로그인',
    'signup.error.name': '이름을 입력해주세요',
    'signup.error.email.required': '이메일을 입력해주세요',
    'signup.error.email.invalid': '올바른 이메일 형식이 아닙니다',
    'signup.error.password.required': '비밀번호를 입력해주세요',
    'signup.error.password.short': '비밀번호는 최소 6자 이상이어야 합니다',
    'signup.error.password.mismatch': '비밀번호가 일치하지 않습니다',
    'signup.error.general': '오류가 발생했습니다. 다시 시도해 주세요.',
    
    // Dashboard Page
    'dashboard.welcome': '다시 오신 것을 환영합니다',
    'dashboard.subtitle': '맞춤형 대학 입학 분석 및 추천 결과입니다.',
    'dashboard.empty.title': '프로필을 완성해주세요',
    'dashboard.empty.desc': '맞춤형 대학 추천을 보려면 먼저 학업 프로필을 완성해주세요.',
    'dashboard.empty.button': '프로필 분석 시작하기',
    'dashboard.stat.profile': '프로필 점수',
    'dashboard.stat.gpa': 'GPA',
    'dashboard.stat.sat': 'SAT Score',
    'dashboard.stat.act': 'ACT Score',
    'dashboard.stat.activities': '활동',
    'dashboard.recommendations.title': '학교 추천',
    'dashboard.category.safety': '안전권 학교',
    'dashboard.category.target': '적정권 학교',
    'dashboard.category.reach': '도전권 학교',
    'dashboard.category.prestige': '명문 학교',
    'dashboard.badge.high': '합격 가능성 높음',
    'dashboard.badge.suitable': '적합함',
    'dashboard.badge.challenge': '도전 목표',
    'dashboard.chance': '합격 가능성',
    'dashboard.strengthen': '강화 필요',
    'dashboard.profile.title': '프로필 요약',
    'dashboard.profile.major': '희망 전공',
    'dashboard.profile.undecided': '미정',
    'dashboard.profile.sat': 'SAT',
    'dashboard.profile.act': 'ACT',
    'dashboard.profile.toefl': 'TOEFL',
    'dashboard.profile.ap': 'AP 과목',
    'dashboard.profile.activities': '활동',
    'dashboard.profile.leadership': '리더십',
    'dashboard.profile.nottaken': '미응시',
    'dashboard.improve.title': '강화가 필요한 영역',
    'dashboard.improve.desc': '합격 가능성을 높이기 위해 이 영역을 개선하는 데 집중하세요.',
    'dashboard.improve.excellent': '훌륭합니다! 모든 영역에서 프로필이 강력해 보입니다.',
    'dashboard.improve.findconsulting': '컨설팅 프로그램 찾기',
    'dashboard.actions.title': '빠른 실행',
    'dashboard.actions.browse': '더 많은 대학교 둘러보기',
    'dashboard.actions.compare': '학교 비교하기',
    'dashboard.actions.update': '프로필 업데이트',
    'dashboard.school.acceptance': '합격률',
    'dashboard.notavailable': 'N/A',
    'dashboard.favorites.title': '관심 학교',
    'dashboard.favorites.saved': '저장된 학교',
  },
  en: {
    // Navbar
    'nav.universities': 'Browse Schools',
    'nav.universities.all': 'View All Schools',
    'nav.universities.compare': 'Compare Schools',
    'nav.universities.map': 'Map View',
    
    // University Map Page
    'map.title': 'University Map',
    'map.subtitle': 'Explore major U.S. universities and their tuition information at a glance',
    'map.universities.count': 'universities displayed',
    'map.reset.view': 'Reset View',
    
    'nav.profile': 'Profile Analysis',
    'nav.consulting': 'Consulting',
    'nav.housing': 'Housing Support',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.language': '한국어',
    
    // HomePage - Hero
    'home.hero.subtitle': 'AI-Powered Study Abroad Roadmap',
    'home.hero.title': 'Your Dream University, Made Reality',
    'home.hero.description': 'Navigate complex admissions at a glance and get your personalized study plan.\nStart your successful U.S. college journey with PrepLounge.',
    'home.hero.cta.predict': 'Predict Admission',
    'home.hero.cta.input': 'Browse Info',
    
    // HomePage - Calculator
    'home.calculator.title': 'Preview Your Admission Chances',
    'home.calculator.subtitle': 'Enter your grades and check your profile score.',
    'home.calculator.gpa': 'GPA (4.0 Scale)',
    'home.calculator.sat.ebrw': 'SAT EBRW (800 max)',
    'home.calculator.sat.math': 'SAT Math (800 max)',
    'home.calculator.score': 'Profile Score',
    'home.calculator.score.total': '/ 100',
    'home.calculator.description': 'This is a simple calculation based on GPA and SAT scores.\nFor comprehensive analysis including extracurricular activities, essays,\nand personalized university recommendations, please complete your full profile.',
    'home.calculator.button': 'Get Detailed Admission Analysis',
    
    // HomePage - Features
    'home.features.title': 'Key Services',
    'home.features.subtitle': 'PrepLounge provides diverse services for successful college admissions for international school students.',
    'home.features.schools.title': 'School\nInformation',
    'home.features.schools.description': 'View admission information for over 1,200 U.S. universities, including required documents and application deadlines.',
    'home.features.profile.title': 'Personalized\nProfile Analysis',
    'home.features.profile.description': 'AI analyzes your admission chances based on your grades and extracurricular activities.',
    'home.features.consulting.title': 'Consulting Programs\nComparison',
    'home.features.consulting.description': 'Compare domestic consulting academies and find the best programs to strengthen your profile.',
    'home.features.link': 'Go →',
    
    // HomePage - Majors
    'home.majors.title': 'Still Wondering About Your Major?',
    'home.majors.subtitle': 'Find your ideal major with a simple test.\n* Average salary and employment rates are estimates.',
    'home.majors.engineering': 'Engineering',
    'home.majors.engineering.specializations': 'Computer Science, Electrical Engineering, Mechanical Engineering',
    'home.majors.engineering.salary': 'Avg. Salary $85,000',
    'home.majors.engineering.employment': '94% Employment',
    'home.majors.engineering.opt': '3-Year STEM OPT Available',
    'home.majors.business': 'Business',
    'home.majors.business.specializations': 'Business, Economics, Finance, Marketing',
    'home.majors.business.salary': 'Avg. Salary $78,000',
    'home.majors.business.employment': '88% Employment',
    'home.majors.business.networking': 'Rich Networking Opportunities',
    'home.majors.liberal': 'Liberal Arts',
    'home.majors.liberal.specializations': 'Literature, Philosophy, History, Linguistics, Cultural Studies',
    'home.majors.liberal.salary': 'Avg. Salary $65,000',
    'home.majors.liberal.employment': '82% Employment',
    'home.majors.liberal.thinking': 'Critical Thinking Development',
    'home.majors.natural': 'Natural Sciences',
    'home.majors.natural.specializations': 'Biology, Chemistry, Physics, Mathematics, Environmental Science',
    'home.majors.natural.salary': 'Avg. Salary $72,000',
    'home.majors.natural.employment': '85% Employment',
    'home.majors.natural.graduate': 'High Grad School Rate',
    'home.majors.social': 'Social Sciences',
    'home.majors.social.specializations': 'Psychology, Political Science, Sociology, International Relations',
    'home.majors.social.salary': 'Avg. Salary $68,000',
    'home.majors.social.employment': '83% Employment',
    'home.majors.social.problem': 'Social Problem Solving',
    
    // Student Profile Page
    'profile.hero.title': 'Profile Analysis',
    'profile.hero.description': 'Complete your academic and extracurricular profile to get a comprehensive profile score and personalized university recommendations.',
    'profile.score.label': 'Profile Score',
    'profile.score.excellent': 'Excellent',
    'profile.score.very-good': 'Very Good',
    'profile.score.good': 'Good',
    'profile.score.fair': 'Fair',
    'profile.score.needs-improvement': 'Needs Improvement',
    'profile.checklist.title': 'Application Components Checklist',
    'profile.checklist.description': 'Check the items you have completed or possess. This helps assess your application readiness.\nNot all items are required and requirements may vary by school.',
    'profile.checklist.gpa': 'Secondary School GPA',
    'profile.checklist.gpa.desc': 'Secondary school GPA',
    'profile.checklist.rank': 'Secondary School Rank',
    'profile.checklist.rank.desc': 'Secondary school rank',
    'profile.checklist.transcript': 'Secondary School Transcript',
    'profile.checklist.transcript.desc': 'Secondary school transcript',
    'profile.checklist.college-prep': 'College Prep Program',
    'profile.checklist.college-prep.desc': 'College-preparatory program',
    'profile.checklist.recommendations': 'Recommendations',
    'profile.checklist.recommendations.desc': 'Recommendations',
    'profile.checklist.extracurriculars': 'Extracurricular Activities',
    'profile.checklist.extracurriculars.desc': 'Extracurricular activities',
    'profile.checklist.essay': 'Personal Statement/Essay',
    'profile.checklist.essay.desc': 'Personal statement or essay',
    'profile.checklist.test-scores': 'Test Scores',
    'profile.checklist.test-scores.desc': 'Test scores',
    'profile.tabs.academic': 'Academic',
    'profile.tabs.non-academic': 'Non-Academic',
    'profile.academic.title': 'Academic Information',
    'profile.academic.gpa': 'GPA (4.0 Scale) *',
    'profile.academic.major': 'Intended Major',
    'profile.academic.major.placeholder': 'Select a major',
    'profile.academic.major.cs': 'Computer Science',
    'profile.academic.major.engineering': 'Engineering',
    'profile.academic.major.business': 'Business',
    'profile.academic.major.medicine': 'Medicine',
    'profile.academic.major.liberal-arts': 'Liberal Arts',
    'profile.academic.major.sciences': 'Sciences',
    'profile.academic.major.math': 'Mathematics',
    'profile.academic.major.other': 'Other',
    'profile.academic.test': 'Standardized Test',
    'profile.academic.test.placeholder': 'Select a test (optional)',
    'profile.academic.sat.ebrw': 'SAT EBRW (800 max)',
    'profile.academic.sat.math': 'SAT Math (800 max)',
    'profile.academic.act': 'ACT Score (36 max)',
    'profile.academic.english': 'English Proficiency Test (International Students)',
    'profile.academic.english.placeholder': 'Select a test (optional)',
    'profile.academic.english.score': 'Score',
    'profile.non-academic.title': 'Non-Academic Information',
    'profile.non-academic.essay': 'Personal Statement (Common App Essay)',
    'profile.non-academic.essay.placeholder': 'Write your personal statement...',
    'profile.non-academic.essay.count': 'characters',
    'profile.extracurriculars.title': 'Extracurricular Activities',
    'profile.extracurriculars.add': 'Add Activity',
    'profile.extracurriculars.activity': 'Activity',
    'profile.extracurriculars.type': 'Activity Type',
    'profile.extracurriculars.type.sports': 'Sports',
    'profile.extracurriculars.type.arts': 'Arts',
    'profile.extracurriculars.type.community': 'Community Service',
    'profile.extracurriculars.type.research': 'Research',
    'profile.extracurriculars.type.academic': 'Academic Clubs',
    'profile.extracurriculars.type.leadership': 'Leadership',
    'profile.extracurriculars.type.work': 'Work Experience',
    'profile.extracurriculars.type.other': 'Other',
    'profile.extracurriculars.name': 'Activity Name',
    'profile.extracurriculars.name.placeholder': 'e.g., Soccer Club',
    'profile.extracurriculars.grades': 'Grade Participation (select all that apply)',
    'profile.extracurriculars.grade': 'th grade',
    'profile.extracurriculars.recognition': 'Recognition Level',
    'profile.extracurriculars.recognition.local': 'Local',
    'profile.extracurriculars.recognition.regional': 'Regional',
    'profile.extracurriculars.recognition.national': 'National',
    'profile.extracurriculars.recognition.international': 'International',
    'profile.extracurriculars.hours': 'Hours per Week',
    'profile.extracurriculars.description': 'Description',
    'profile.extracurriculars.description.placeholder': 'Describe your role and accomplishments...',
    'profile.extracurriculars.empty': 'No extracurricular activities added yet.',
    'profile.extracurriculars.empty.action': 'Click "Add Activity" to get started.',
    'profile.recommendations.title': 'Recommendation Letters',
    'profile.recommendations.add': 'Add Recommendation',
    'profile.recommendations.letter': 'Recommendation',
    'profile.recommendations.source': 'Recommender',
    'profile.recommendations.source.teacher': 'Teacher',
    'profile.recommendations.source.counselor': 'Counselor',
    'profile.recommendations.source.principal': 'Principal',
    'profile.recommendations.source.coach': 'Coach',
    'profile.recommendations.source.employer': 'Employer',
    'profile.recommendations.source.other': 'Other',
    'profile.recommendations.depth': 'Relationship Depth',
    'profile.recommendations.depth.deep': 'Knows deeply',
    'profile.recommendations.depth.somewhat': 'Knows somewhat',
    'profile.recommendations.depth.barely': 'Barely knows',
    'profile.recommendations.relevance': 'Subject/Field Relevance',
    'profile.recommendations.relevance.highly': 'Highly relevant to intended major',
    'profile.recommendations.relevance.somewhat': 'Somewhat relevant to intended major',
    'profile.recommendations.relevance.not': 'Not relevant or not available',
    'profile.recommendations.empty': 'No recommendation letters added yet.',
    'profile.recommendations.empty.action': 'Click "Add Recommendation" to get started.',
    'profile.legacy.title': 'Legacy Status',
    'profile.legacy.yes': 'Yes',
    'profile.legacy.no': 'No',
    'profile.citizenship.title': 'Citizenship',
    'profile.citizenship.domestic': 'Domestic',
    'profile.citizenship.international': 'International',
    'profile.save': 'Calculate Profile Score',
    'profile.comparison.title': 'School Comparison',
    'profile.comparison.search.placeholder': 'Search by school name...',
    'profile.comparison.search.button': 'Search',
    'profile.comparison.results': 'Search Results',
    'profile.comparison.ranking': 'Acceptance Rate',
    'profile.comparison.category.safety': 'Safety',
    'profile.comparison.category.target': 'Target',
    'profile.comparison.category.reach': 'Reach',
    'profile.comparison.required-score': 'Required Score:',
    'profile.comparison.my-score': 'My Score:',
    'profile.comparison.ratio': 'Ratio:',
    'profile.comparison.no-results': 'No schools found matching',
    'profile.comparison.no-results.action': 'Try searching with a different name.',
    'profile.comparison.empty': 'Complete your profile to view comparison results.',
    
    // Housing Page
    'housing.hero.subtitle': 'Searching for your Dream Home',
    'housing.hero.title': 'Find Your Perfect Home Near Campus.',
    'housing.hero.description': 'Browse all listings near your university at a glance!\nFind your ideal home online, easily and conveniently.',
    'housing.hero.button': 'Find Properties Now',
    'housing.availability.notice': 'Currently available in California and Georgia only',
    'housing.search.title': 'Search Easily with Your Preferences',
    'housing.search.description': 'Search cities in California or Georgia',
    'housing.search.placeholder': 'e.g., Los Angeles, Atlanta, Fresno, Savannah',
    'housing.search.error.invalid-state': 'Sorry, listings are currently available only in California (CA) and Georgia (GA).',
    'housing.search.error.examples': 'Examples: Fresno, Los Angeles, San Francisco (CA) • Atlanta, Savannah, Athens (GA)',
    'housing.listings.title': 'New Listings Near Harvard',
    'housing.badge.available': 'Available',
    'housing.price.period': '/mo',
    'housing.button.details': 'View Details',
    'housing.empty.title': 'No listings found in',
    'housing.empty.description': 'Listings are currently available in California and Georgia only.',
    'housing.empty.examples': 'California: Fresno, Los Angeles, San Francisco, San Diego, Sacramento',
    'housing.empty.examples.ga': 'Georgia: Atlanta, Savannah, Athens, Augusta, Columbus',
    'housing.features.title': 'Easier and Faster Way to Find Housing',
    'housing.features.location.title': 'Curated Near Universities',
    'housing.features.location.description': 'Search by university location and automatically filter for properties near campus.\nFind only the homes you need instead of thousands of irrelevant listings.',
    'housing.features.search.title': 'Search by Your Preferences',
    'housing.features.search.description': 'Select your preferred criteria like budget, bedrooms, distance, and property type to see only matching listings.\nFind your perfect home with just a few clicks without complex searches.',
    'housing.features.expert.title': 'Expert Consultation for First-Timers',
    'housing.features.expert.description': 'Finding housing in the U.S. for the first time and feeling overwhelmed? Get convenient consultation with local real estate experts via KakaoTalk.',
    
    // Universities Page
    'universities.title': 'Find Universities',
    'universities.description': 'Browse U.S. universities and find schools that match your profile.',
    'universities.search.placeholder': 'Search by name or location',
    'universities.filter.title': 'Filter',
    'universities.filter.type': 'Institution Type',
    'universities.filter.type.private': 'Private',
    'universities.filter.type.public': 'Public',
    'universities.filter.sort': 'Sort By',
    'universities.filter.sort.default': 'Recommended',
    'universities.filter.sort.name-asc': 'Alphabetical (A–Z)',
    'universities.filter.sort.name-desc': 'Alphabetical (Z–A)',
    'universities.filter.sort.sat-asc': 'SAT Range (Ascending)',
    'universities.filter.sort.sat-desc': 'SAT Range (Descending)',
    'universities.filter.tuition': 'Tuition',
    'universities.filter.sat': 'SAT Range',
    'universities.results': 'Showing {filtered} of {total} schools',
    'universities.acceptance': 'Acceptance Rate:',
    'universities.tuition': 'Tuition:',
    'universities.sat': 'SAT Range:',
    'universities.act': 'ACT Range:',
    'universities.empty.title': 'No schools match your criteria',
    'universities.empty.description': 'Try resetting the filters or search again.',
    'universities.empty.reset': 'Reset Filters',
    
    // University Profile Page
    'university.back': 'Back to Schools List',
    'university.commonapp.yes': 'Common App Available',
    'university.commonapp.no': 'School-Specific Application Required',
    'university.compare': 'Compare',
    'university.addToFavorites': 'Add to Favorites',
    'university.removeFromFavorites': 'Remove from Favorites',
    'university.location': 'Location',
    'university.type': 'Type',
    'university.size': 'Size',
    'university.stat.acceptance': 'Acceptance Rate',
    'university.stat.tuition': 'Tuition',
    'university.stat.sat': 'SAT Range',
    'university.stat.act': 'ACT Range',
    'university.stat.gpa': 'Average GPA',
    'university.requirements.title': 'Admission Requirements',
    'university.requirements.gpa': 'High School GPA',
    'university.requirements.required': 'Required',
    'university.info.title': 'Academic Information',
    'university.info.graduation': 'Graduation Rate',
    'university.notfound.title': 'School Not Found',
    'university.notfound.back': 'Back to Schools List',
    
    // Login Page
    'login.title': 'Login',
    'login.subtitle': 'Welcome back to PrepLounge',
    'login.email': 'Email',
    'login.email.placeholder': 'Enter your email address',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.button': 'Login',
    'login.loading': 'Logging in...',
    'login.signup.prompt': "Don't have an account yet?",
    'login.signup.link': 'Sign up',
    'login.error.invalid': 'Email or password is incorrect.',
    'login.error.general': 'An error occurred. Please try again.',
    
    // Signup Page
    'signup.title': 'Sign Up',
    'signup.subtitle': 'Start your journey to your dream university',
    'signup.name': 'Full Name',
    'signup.name.placeholder': 'Enter your full name',
    'signup.email': 'Email',
    'signup.email.placeholder': 'Enter your email address',
    'signup.password': 'Password',
    'signup.password.placeholder': 'Enter your password',
    'signup.confirm': 'Confirm Password',
    'signup.confirm.placeholder': 'Re-enter your password',
    'signup.terms.agree': 'I agree to the',
    'signup.terms.service': 'Terms of Service',
    'signup.terms.and': 'and',
    'signup.terms.privacy': 'Privacy Policy',
    'signup.button': 'Create Account',
    'signup.loading': 'Creating account...',
    'signup.login.prompt': 'Already have an account?',
    'signup.login.link': 'Sign in',
    'signup.error.name': 'Name is required',
    'signup.error.email.required': 'Email is required',
    'signup.error.email.invalid': 'Invalid email format',
    'signup.error.password.required': 'Password is required',
    'signup.error.password.short': 'Password must be at least 6 characters',
    'signup.error.password.mismatch': 'Passwords do not match',
    'signup.error.general': 'An error occurred. Please try again.',
    
    // Dashboard Page
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Your personalized college admission analysis and recommendations.',
    'dashboard.empty.title': 'Complete Your Profile',
    'dashboard.empty.desc': 'To see personalized university recommendations, please complete your academic profile first.',
    'dashboard.empty.button': 'Start Profile Analysis',
    'dashboard.stat.profile': 'Profile Score',
    'dashboard.stat.gpa': 'GPA',
    'dashboard.stat.sat': 'SAT Score',
    'dashboard.stat.act': 'ACT Score',
    'dashboard.stat.activities': 'Activities',
    'dashboard.recommendations.title': 'School Recommendations',
    'dashboard.category.safety': 'Safety Schools',
    'dashboard.category.target': 'Target Schools',
    'dashboard.category.reach': 'Reach Schools',
    'dashboard.category.prestige': 'Prestige Schools',
    'dashboard.badge.high': 'High Chance',
    'dashboard.badge.suitable': 'Good Fit',
    'dashboard.badge.challenge': 'Reach Goal',
    'dashboard.chance': 'Admission Chance',
    'dashboard.strengthen': 'Strengthen',
    'dashboard.profile.title': 'Profile Summary',
    'dashboard.profile.major': 'Intended Major',
    'dashboard.profile.undecided': 'Undecided',
    'dashboard.profile.sat': 'SAT',
    'dashboard.profile.act': 'ACT',
    'dashboard.profile.toefl': 'TOEFL',
    'dashboard.profile.ap': 'AP Courses',
    'dashboard.profile.activities': 'Activities',
    'dashboard.profile.leadership': 'Leadership',
    'dashboard.profile.nottaken': 'Not Taken',
    'dashboard.improve.title': 'Areas to Strengthen',
    'dashboard.improve.desc': 'Focus on improving these areas to increase your admission chances.',
    'dashboard.improve.excellent': 'Excellent! Your profile looks strong across all areas.',
    'dashboard.improve.findconsulting': 'Find Consulting Programs',
    'dashboard.actions.title': 'Quick Actions',
    'dashboard.actions.browse': 'Browse More Universities',
    'dashboard.actions.compare': 'Compare Schools',
    'dashboard.actions.update': 'Update Profile',
    'dashboard.school.acceptance': 'acceptance',
    'dashboard.notavailable': 'N/A',
    'dashboard.favorites.title': 'Favorite Schools',
    'dashboard.favorites.saved': 'Saved Schools',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'ko') ? saved : 'ko';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
